// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Script, console} from "forge-std/Script.sol";
import {JWKRegistry} from "../src/JWKRegistry.sol";

/// @title Register Google JWK Script
/// @notice Registers a Google OAuth RSA public key in JWKRegistry
/// @dev Run this after deployment to register actual Google keys
///      Use jwkToLimbs.js to get the limbs from Google's JWKS endpoint
contract RegisterGoogleJWKScript is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        address registryAddress = vm.envAddress("JWK_REGISTRY_ADDRESS");

        // Load key ID and limbs from environment
        // These should be generated by running: node poc/scripts/jwkToLimbs.js
        string memory kid = vm.envString("JWK_KID");

        vm.startBroadcast(deployerPrivateKey);

        JWKRegistry registry = JWKRegistry(registryAddress);

        // Parse limbs from environment (comma-separated hex values)
        bytes32[18] memory limbs = _parseLimbs();

        // Register the key
        registry.registerKey(kid, limbs);

        // Verify registration
        bytes32 keyHash = registry.computeKeyHash(limbs);
        bool isValid = registry.isValidKeyHash(keyHash);

        console.log("Registered key:", kid);
        console.log("Key hash:");
        console.logBytes32(keyHash);
        console.log("Is valid:", isValid);

        vm.stopBroadcast();
    }

    function _parseLimbs() internal view returns (bytes32[18] memory) {
        bytes32[18] memory limbs;

        // Read each limb from environment variables JWK_LIMB_0 through JWK_LIMB_17
        limbs[0] = bytes32(vm.envUint("JWK_LIMB_0"));
        limbs[1] = bytes32(vm.envUint("JWK_LIMB_1"));
        limbs[2] = bytes32(vm.envUint("JWK_LIMB_2"));
        limbs[3] = bytes32(vm.envUint("JWK_LIMB_3"));
        limbs[4] = bytes32(vm.envUint("JWK_LIMB_4"));
        limbs[5] = bytes32(vm.envUint("JWK_LIMB_5"));
        limbs[6] = bytes32(vm.envUint("JWK_LIMB_6"));
        limbs[7] = bytes32(vm.envUint("JWK_LIMB_7"));
        limbs[8] = bytes32(vm.envUint("JWK_LIMB_8"));
        limbs[9] = bytes32(vm.envUint("JWK_LIMB_9"));
        limbs[10] = bytes32(vm.envUint("JWK_LIMB_10"));
        limbs[11] = bytes32(vm.envUint("JWK_LIMB_11"));
        limbs[12] = bytes32(vm.envUint("JWK_LIMB_12"));
        limbs[13] = bytes32(vm.envUint("JWK_LIMB_13"));
        limbs[14] = bytes32(vm.envUint("JWK_LIMB_14"));
        limbs[15] = bytes32(vm.envUint("JWK_LIMB_15"));
        limbs[16] = bytes32(vm.envUint("JWK_LIMB_16"));
        limbs[17] = bytes32(vm.envUint("JWK_LIMB_17"));

        return limbs;
    }
}
